name: pillow
description: "Health Tracking App"
publish_to: 'none'

version: 2.1.1+6

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.6.0
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  percent_indicator: ^4.2.4
  pretty_animated_text: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  fl_chart: ^0.65.0
  tflite_flutter: ^0.11.0
  pdf: ^3.10.7
  share_plus: ^11.0.0
  flutter_local_notifications: ^19.0.0
  permission_handler: ^12.0.0+1
  just_audio: ^0.10.3
  url_launcher: ^6.2.5
  http: ^1.2.0
  html: ^0.15.4
  shared_preferences: ^2.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

dependency_overrides:
  timezone: ^0.9.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/models/
    - assets/models/symptom_prediction/model.tflite
    - assets/models/symptom_prediction/tokenizer.json
    - assets/models/symptom_prediction/mlb.json
    - assets/audio-tracks/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit.ttf
